### ISSUE TITLE
Long file name and other Errors

### ISSUE THREAD

**Issue by sarangtc** [EricZimmerman/LECmd#1]
I often get 2 errors:
1) Index was outside the bounds of the array.
2) The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

Is there a way to fix these (without renaming/moving the files)?

**Comment by EricZimmerman** [comment]
Is this on a live system? Do other tools parse the lnk files? Can you share them?

You can use kape to pull back lnk files and then lecmd them if you have long path issues.

**Comment by sarangtc** [comment]
Yes, this is on a live system.
**error 1**: the lnk file itself is corrupt (0kb)
**error 2**: the **LnkParse3** python package (https://github.com/Matmaus/LnkParse3) parses lnk files with long filenames without an error

**Comment by EricZimmerman** [comment]
That doesn't mean the python tool is parsing everything just because it handles long paths

How are you ending up with lnk files in a long path anyways?

As to the 0kb files I suppose I can just ignore them

**Comment by EricZimmerman** [comment]
Please show me a screenshot of the long path error so I can try to recreate it and then come up with a workaround.

**Comment by EricZimmerman** [comment]
i made some changes to LECmd and have a build you can test. see attached and let me know.

it should ignore 0 byte files now and i enabled long file paths. if long file names do not work i need more info about your setup so i can try to replicate it here

ill attach binary here in a few

**Comment by EricZimmerman** [comment]
This fixes long paths

note that you must have .net 4.6.2 or later

[LECmd.zip](https://github.com/EricZimmerman/LECmd/files/5653196/LECmd.zip)

![image](https://user-images.githubusercontent.com/4265254/101361748-61e63680-386d-11eb-9da1-42e405832cd8.png)

please test it, but ill push official version out now too

**Comment by sarangtc** [comment]
the new version works with long filenames but the output format has changed
before json for unc path would start 
`{"SourceFile":"\\\\SERVERA\\Data\\.......`
but now the json output is:
`{"SourceFile":"\\\\?\\UNC\\SERVERA\\Data\\.......`

**Comment by EricZimmerman** [comment]
thats how long file name support works.

it is what it is. 

do you want long file name support, or the old path format?

**Comment by sarangtc** [comment]
OK. Thanks 

> thats how long file name support works.
> 
> it is what it is.
> 
> do you want long file name support, or the old path format?

I was not aware of this. Thanks for the clarification. I was not sure whether it was intentional or not.
I am fine using the new long format with the extra `?\\UNC\\`

**Comment by EricZimmerman** [comment]
ok i stripped out the prefix stuff when present, so now it looks the same regardless of if its a long path or not. 

check for updates with the ps1 and you will see it
