### ISSUE TITLE
Some fields are garbled if LECmd reads a LNK file which points to a file name consists of multibyte characters

### ISSUE THREAD

**Issue by herosi** [EricZimmerman/LECmd#11]
LECmd and the lnk library do not support multibyte characters in some fields such as such as CommonPath and LocalPath.

Therefore, those fields will be garbled.
I attached a LNK file that can reproduce the problem.
[test_lnk.zip](https://github.com/EricZimmerman/LECmd/files/12585491/test_lnk.zip)

If you use the original version of LECmd, the Local path filed is garbled. You can confirm it like the figure below.
![default](https://github.com/EricZimmerman/LECmd/assets/20717881/f69b9d7e-889f-43cb-872b-71b9ba7fae5d)

So I PRed #10 to solve this. If you use the improved LECmd with --cp 932 option, you will find the string in the Local path is correctly displayed, although you might not be able to understand what the string is. Trust me ;-)
![WithCpOption](https://github.com/EricZimmerman/LECmd/assets/20717881/d70e213c-4724-4404-bda1-823227f47bb6)

The target file name I used is "テスト.txt" means "test.txt" in Japanese. I hope you can distinguish the results above.
Note that before using it, execute "chcp 932" on the command prompt to change the code page into Japanese to display strings correctly.

Although I know you and English speakers do not need this option, it is useful for people who do not speak English.
I hope you take the PR #10 for the people.

If you have any questions, please let me know.

**Comment by EricZimmerman** [comment]
this is on my radar to accept, i just need to go through it. thank you for the sample file.

at least as is, the shell items work properly

**Comment by herosi** [comment]
Thanks for taking the PR! I confirmed the latest LECmd has --cp option and it worked!
