### ISSUE TITLE
--jsonpretty example is not a valid argument

### ISSUE THREAD

**Issue by ItsPaPPy** [EricZimmerman/LECmd#4]
In your [README.md](https://github.com/EricZimmerman/LECmd#readme) as well as the help text, the second example is `LECmd.exe -f "C:\Temp\somelink.lnk" --json "D:\jsonOutput" --jsonpretty`, but --jsonpretty isnt a valid argument. The correct argument should just be --pretty

**Comment by AndrewRathbun** [comment]
https://github.com/EricZimmerman/LECmd/pull/6 resolved this. This can now be closed.
