### ISSUE TITLE
Suggestion: Provide filter options on HeaderFlags

### ISSUE THREAD

**Issue by ItsPaPPy** [EricZimmerman/LECmd#5]
I would love to use your tool to find malicious .LNK files, but on some endpoints there are 2k files to go through. If there was an option to filter by HeaderFlags, for example by which one "HasArguments", it could speed up which files to investigate.

**Comment by EricZimmerman** [comment]
Use CSV and q option. Q is key to speed it up. 2k is nothing to tear thru. Same time for me to process either way. On e in CSV load to TLE then filter or sort on the args column. Done.

**Comment by EricZimmerman** [comment]
Once you identity interesting lnk files in CSV you can use -f for full color glorious details on each file of interest.
